#!/usr/bin/php
<?php
include_once "laravel/vendor/autoload.php";

use Symfony\Component\Console\Application;
use AccessManager\Radius\Commands\AuthorizeCommand;
use AccessManager\Radius\Commands\AccountCommand;

$app = new Application();
$app->add(new AuthorizeCommand);
$app->add(new AccountCommand);
$app->run();

//end of file radius