#!/usr/bin/php
<?php
include_once "laravel/vendor/autoload.php";

use Symfony\Component\Console\Application;
use AccessManager\Radius\Commands\AuthorizeCommand;
use AccessManager\Radius\Commands\AccountCommand;
use AccessManager\Radius\Commands\FrinternetCronCommand;
use AccessManager\Radius\Commands\APCronCommand;
use AccessManager\Invoices\Commands\InvoiceGeneratorCommand;

$app = new Application();
$app->add( new AuthorizeCommand );
$app->add( new AccountCommand );
$app->add( new FrinternetCronCommand );
$app->add( new APCronCommand );
$app->add( new InvoiceGeneratorCommand );
$app->run();

//end of file radius